/**
 * rbac.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Centralized Role-Based Access Control (RBAC) definitions and permission checks.
 */

export type Role =
  | 'SUPER_ADMIN'
  | 'ORG_OWNER'
  | 'ADMIN'
  | 'PROJECT_MANAGER'
  | 'ACCOUNTANT'
  | 'SITE_MANAGER'
  | 'STORE_MANAGER'
  | 'VIEWER';

export type Permission =
  | 'PROJECT_VIEW'
  | 'PROJECT_CREATE'
  | 'PROJECT_UPDATE'
  | 'PROJECT_DELETE'
  | 'MATERIAL_VIEW'
  | 'MATERIAL_CREATE'
  | 'MATERIAL_UPDATE'
  | 'MATERIAL_DELETE'
  | 'CEMENT_VIEW'
  | 'CEMENT_CREATE'
  | 'CEMENT_UPDATE'
  | 'CEMENT_DELETE'
  | 'TAR_VIEW'
  | 'TAR_CREATE'
  | 'TAR_UPDATE'
  | 'TAR_DELETE'
  | 'STOCK_VIEW'
  | 'STOCK_UPDATE'
  | 'EXPENSE_VIEW'
  | 'EXPENSE_CREATE'
  | 'EXPENSE_UPDATE'
  | 'EXPENSE_DELETE'
  | 'PRIVATE_WORK_VIEW'
  | 'PRIVATE_WORK_CREATE'
  | 'PRIVATE_WORK_UPDATE'
  | 'PRIVATE_WORK_DELETE'
  | 'WORK_BASED_ENTRY_VIEW'
  | 'WORK_BASED_ENTRY_CREATE'
  | 'WORK_BASED_ENTRY_UPDATE'
  | 'WORK_BASED_ENTRY_DELETE'
  | 'AUDIT_LOG_VIEW'
  | 'MEMBER_MANAGE'
  | 'ORG_SETTINGS';

const ALL_PERMISSIONS: Permission[] = [
  'PROJECT_VIEW', 'PROJECT_CREATE', 'PROJECT_UPDATE', 'PROJECT_DELETE',
  'MATERIAL_VIEW', 'MATERIAL_CREATE', 'MATERIAL_UPDATE', 'MATERIAL_DELETE',
  'CEMENT_VIEW', 'CEMENT_CREATE', 'CEMENT_UPDATE', 'CEMENT_DELETE',
  'TAR_VIEW', 'TAR_CREATE', 'TAR_UPDATE', 'TAR_DELETE',
  'STOCK_VIEW', 'STOCK_UPDATE',
  'EXPENSE_VIEW', 'EXPENSE_CREATE', 'EXPENSE_UPDATE', 'EXPENSE_DELETE',
  'PRIVATE_WORK_VIEW', 'PRIVATE_WORK_CREATE', 'PRIVATE_WORK_UPDATE', 'PRIVATE_WORK_DELETE',
  'WORK_BASED_ENTRY_VIEW', 'WORK_BASED_ENTRY_CREATE', 'WORK_BASED_ENTRY_UPDATE', 'WORK_BASED_ENTRY_DELETE',
  'AUDIT_LOG_VIEW', 'MEMBER_MANAGE', 'ORG_SETTINGS',
];

const READ_ONLY_PERMISSIONS: Permission[] = [
  'PROJECT_VIEW', 'MATERIAL_VIEW', 'CEMENT_VIEW', 'TAR_VIEW',
  'STOCK_VIEW', 'EXPENSE_VIEW', 'PRIVATE_WORK_VIEW', 'WORK_BASED_ENTRY_VIEW',
];

const ROLE_PERMISSIONS_MAP: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ORG_OWNER: ALL_PERMISSIONS,
  ADMIN: ALL_PERMISSIONS,
  PROJECT_MANAGER: [
    'PROJECT_VIEW', 'PROJECT_CREATE', 'PROJECT_UPDATE',
    'MATERIAL_VIEW', 'MATERIAL_CREATE', 'MATERIAL_UPDATE',
    'CEMENT_VIEW', 'CEMENT_CREATE', 'CEMENT_UPDATE',
    'TAR_VIEW', 'TAR_CREATE', 'TAR_UPDATE',
    'STOCK_VIEW', 'STOCK_UPDATE',
    'WORK_BASED_ENTRY_VIEW', 'WORK_BASED_ENTRY_CREATE', 'WORK_BASED_ENTRY_UPDATE',
    'EXPENSE_VIEW', 'EXPENSE_CREATE',
  ],
  ACCOUNTANT: [
    'PROJECT_VIEW',
    'EXPENSE_VIEW', 'EXPENSE_CREATE', 'EXPENSE_UPDATE', 'EXPENSE_DELETE',
    'PRIVATE_WORK_VIEW', 'PRIVATE_WORK_CREATE', 'PRIVATE_WORK_UPDATE', 'PRIVATE_WORK_DELETE',
    'CEMENT_VIEW', 'TAR_VIEW', 'STOCK_VIEW',
  ],
  SITE_MANAGER: [
    'PROJECT_VIEW',
    'MATERIAL_VIEW', 'MATERIAL_CREATE', 'MATERIAL_UPDATE',
    'CEMENT_VIEW', 'CEMENT_CREATE',
    'TAR_VIEW', 'TAR_CREATE',
    'STOCK_VIEW', 'STOCK_UPDATE',
  ],
  STORE_MANAGER: [
    'STOCK_VIEW', 'STOCK_UPDATE',
    'MATERIAL_VIEW', 'MATERIAL_CREATE',
    'CEMENT_VIEW', 'TAR_VIEW',
  ],
  VIEWER: READ_ONLY_PERMISSIONS,
};

export function hasPermission(role: Role | string, permission: Permission): boolean {
  const normalizedRole = (role || 'VIEWER').toUpperCase() as Role;
  const permissions = ROLE_PERMISSIONS_MAP[normalizedRole] || READ_ONLY_PERMISSIONS;
  return permissions.includes(permission);
}
